services:
  bdk_debug_listener:
    # alias", "parent", "class", "shared", "synthetic", "lazy", "public", "abstract", "deprecated", "factory", "file", "arguments", "properties", "configurator", "calls", "tags", "decorates", "decoration_inner_name", "decoration_priority", "decoration_on_invalid", "autowire", "autoconfigure, bind
    tags: ['kernel.event_subscriber']
    class: bdk\Debug\Framework\Symfony\DebugBundle\EventListener\BdkDebugBundleListener
    arguments: ['@bdk\Debug']
  bdk\Debug:
    factory: ['bdk\Debug', 'getInstance']
  monologHandler:
   class: bdk\Debug\Collector\MonologHandler
   arguments: ['@bdk\Debug']
   tags: ['monolog.logger']
            # - { name: monolog.logger, channel: country }