services:
  # KEYS
  #
  # "alias"
  # "parent"
  # "class"
  # "shared"
  # "synthetic"
  # "lazy"
  # "public"
  # "abstract"
  # "deprecated"
  # "factory"
  # "file"
  # "arguments"
  # "properties"
  # "configurator"
  # "calls"
  # "tags"
  # "decorates"
  # "decoration_inner_name"
  # "decoration_priority"
  # "decoration_on_invalid"
  # "autowire"
  # "autoconfigure"
  # "bind"
  bdk_debug:
    class: bdk\Debug
    factory: ['bdk\Debug', 'getInstance']
  bdk_debug_listener:
    class: bdk\Debug\Framework\Symfony\DebugBundle\EventListener\BdkDebugBundleListener
    arguments: ['@bdk_debug', '@doctrine']
    tags: ['kernel.event_subscriber']
  bdk_debug_twig:
    class: bdk\Debug\Collector\TwigExtension
    arguments: ['@bdk_debug']
    tags: ['twig.extension']
  monologHandler:
   class: bdk\Debug\Collector\MonologHandler
   arguments: ['@bdk_debug']
   tags: ['monolog.logger']
        # - { name: monolog.logger, channel: country }
